version: '3.1'

services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - 3008:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5437
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_password
      MB_DB_HOST: host.docker.internal

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_password
      POSTGRES_DB: metabase
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5437:5432