version: '3'

services:
    
  swagger-ui:
    restart: always
    image: swaggerapi/swagger-ui:latest
    ports:
      - "${SWAGGER_PORT}:8080"
    environment:
      - API_URL=http://localhost:${POSTGREST_PORT}/    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: recep@gmail.com
      PGADMIN_DEFAULT_PASSWORD: recep123
    ports:
      - ${PGADMIN_PORT}:80