# Use the official Docker Hub pgAdmin image
FROM dpage/pgadmin4:latest

# Set environment variables
ENV PGADMIN_DEFAULT_EMAIL recep@gmail.com
ENV PGADMIN_DEFAULT_PASSWORD recep123

# Expose the pgAdmin port
EXPOSE 80

# Set the default command to run when starting the container
CMD ["pgadmin4"]